[project]
name = "EchoMind"
version = "0.1.0"

[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]  # Critical for src-layout